### ISSUE TITLE
Typo in the Bibtex

### ISSUE THREAD

**Issue by hmyang0727** [kky7/MSSNet#1]
Thank you for your nice work.

I found that there is a typo in your Bibtex.

https://github.com/kky7/MSSNet/blob/e4e27571ac2a71cef115e9205281145d46d1d99b/README.md?plain=1#L99

`booktitle = {Proc. of ECCVW (AIM)}
year = {2022},`

needs to be changed like:

`booktitle = {Proc. of ECCVW (AIM)},
year = {2022}`

In order to cite it correctly.

Regards,
Heemin

**Comment by kky7** [comment]
Thank you for letting me know.
I changed that part.

Regards,
Kiyeon
